version: '3'

services:
    app:
        build: .
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 120s ./.docker/entrypoint.sh
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - app-network
    nginx:
        build: ./.docker/nginx
        container_name: nginx
        entrypoint: dockerize -template ./nginx.tmpl:./nginx.conf nginx -g 'daemon off;'
        restart: always
        tty: true
        environment:
          - HOST=app
          - PORT=9000
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
